const MAKE_REQUEST = "MAKE_REQUEST"
const POSTS_LOADED = "POSTS_LOADED"
const FAIL_REQUEST = "FAIL_REQUEST"
const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
const CREATE_POST_FAILURE = "CREATE_POST_FAILURE"


const ADD_POST = "ADD_POST"
const DELETE_POST = "DELETE_POST"
const UPDATE_POST = "UPDATE_POST"
const SAVE_UPDATE_POST = "SAVE_UPDATE_POST"

export {
  ADD_POST, 
  DELETE_POST,
  UPDATE_POST,
  MAKE_REQUEST,
  FAIL_REQUEST,
  POSTS_LOADED,
  SAVE_UPDATE_POST,
  CREATE_POST_FAILURE,
  CREATE_POST_SUCCESS,
}